version: "3"

services:
  database:
    image: postgres:alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: venususer
      POSTGRES_DB: venusdb
      POSTGRES_PASSWORD: venuspassword