version: '3'

services:
  database:
    container_name: fairland_postgres_db
    image: postgres:alpine
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'fairlanduser'
      POSTGRES_DB: 'fairlanddb'
      POSTGRES_PASSWORD: 'fairlandpassword'
