name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Install doctl 
        uses: digitalocean/action-doctl@v2
        with:
          token: 713dc417a459cbca6408390efff34c441a3a097efa066d4cb9271eb790f51116
          
      - name: Log in to DO Container Registry 
        run: doctl registry login --expiry-seconds 600
        
      - name: Tag image 
        run:
          docker tag sample/my-page \
          registry.digitalocean.com/my-sample-registry/my-sample-page:${{github.event.inputs.version }}
      - name: Push image to DO Container Registry 
        run: docker push registry.digitalocean.com/my-sample-registry/my-sample-page:${{ github.event.inputs.version }}
