name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Build, Push and Deploy to Heroku 
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }} # your heroku api key
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }} # you aplication name
          dockerfile_directory: ./
          dockerfile_name: dockerfile
          docker_options: "--no-cache"
          process_type: web
