name: Docker Image CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Checkout files
      
      - name: Digital Ocean Deploy App
      - uses: jjst/action-digitalocean-deploy-app@v2
        with:
          token: c4a5f670dd3c322c1d741ae2f07ba3f90dc79727bc7154c096abe7253158e805
