name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Install doctl 
        uses: digitalocean/action-doctl@v2
        with:
          token: 62b11fdfafc374d8a491402c1cd9c53fd4725d43e0ccaf9c0a150e96f12b1a27
